"""
Dataset and DataLoader utilities for BDD100K

Handles:
- Loading BDD100K images + segmentation masks
- Loading pseudo-depth labels (generated by Depth Anything v2)
- Loading lane annotations
"""

import os
import json
import numpy as np
import torch
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from PIL import Image


# ImageNet normalization (used by EfficientNet)
IMAGENET_MEAN = [0.485, 0.456, 0.406]
IMAGENET_STD = [0.229, 0.224, 0.225]

# Input resolution (H, W) — 320x640 is a good balance for Colab
INPUT_SIZE = (320, 640)


class BDD100KDataset(Dataset):
    """BDD100K dataset for multi-task learning.

    Args:
        root_dir: path to BDD100K image root (contains images/)
        split: 'train' or 'val'
        tasks: list of tasks to load, e.g. ['seg', 'depth', 'lanes']
        seg_root: separate root for segmentation masks (contains train/, val/)
        depth_root: separate root for depth maps (contains train/, val/)
        transform: optional additional transforms
    """

    def __init__(self, root_dir, split='train', tasks=None,
                 seg_root=None, depth_root=None, transform=None):
        self.root_dir = root_dir
        self.split = split
        self.tasks = tasks or ['seg', 'depth']
        self.transform = transform

        # Image directory — try 10k first, then 100k
        self.img_dir = os.path.join(root_dir, 'images', '10k', split)
        if not os.path.exists(self.img_dir):
            self.img_dir = os.path.join(root_dir, 'images', '100k', split)

        # Collect image filenames
        self.filenames = sorted([
            f for f in os.listdir(self.img_dir)
            if f.endswith(('.jpg', '.png'))
        ])

        # Segmentation mask directory
        if seg_root:
            self.seg_dir = os.path.join(seg_root, split)
        else:
            self.seg_dir = os.path.join(root_dir, 'labels', 'sem_seg', 'masks', split)

        # Depth directory
        if depth_root:
            split_path = os.path.join(depth_root, split)
            self.depth_dir = split_path if os.path.exists(split_path) else depth_root
        else:
            self.depth_dir = os.path.join(root_dir, 'labels', 'depth', split)

        # Lane segmentation directory
        self.lane_dir = os.path.join(root_dir, 'labels', 'lane', 'masks', split)

        # Standard image transforms
        self.img_transform = transforms.Compose([
            transforms.Resize(INPUT_SIZE),
            transforms.ToTensor(),
            transforms.Normalize(mean=IMAGENET_MEAN, std=IMAGENET_STD),
        ])

    def __len__(self):
        return len(self.filenames)

    def __getitem__(self, idx):
        filename = self.filenames[idx]
        basename = os.path.splitext(filename)[0]

        # Load and transform image
        img_path = os.path.join(self.img_dir, filename)
        image = Image.open(img_path).convert('RGB')
        image = self.img_transform(image)

        sample = {'image': image, 'filename': basename}

        # Load segmentation mask
        if 'seg' in self.tasks:
            seg_path = os.path.join(self.seg_dir, basename + '.png')
            if os.path.exists(seg_path):
                seg = Image.open(seg_path)
                seg = seg.resize((INPUT_SIZE[1], INPUT_SIZE[0]),
                                 Image.NEAREST)
                seg = torch.from_numpy(np.array(seg)).long()
            else:
                seg = torch.zeros(INPUT_SIZE, dtype=torch.long)
            sample['seg'] = seg

        # Load depth map
        if 'depth' in self.tasks:
            depth_path = os.path.join(self.depth_dir, basename + '.npy')
            if os.path.exists(depth_path):
                depth = np.load(depth_path).astype(np.float32)
                depth = torch.from_numpy(depth).unsqueeze(0)
                depth = torch.nn.functional.interpolate(
                    depth.unsqueeze(0), size=INPUT_SIZE, mode='bilinear',
                    align_corners=False
                ).squeeze(0)
            else:
                depth = torch.zeros((1, *INPUT_SIZE), dtype=torch.float32)
            sample['depth'] = depth

        # Load lane mask
        if 'lanes' in self.tasks:
            lane_path = os.path.join(self.lane_dir, basename + '.png')
            if os.path.exists(lane_path):
                lane = Image.open(lane_path)
                lane = lane.resize(
                    (INPUT_SIZE[1] // 4, INPUT_SIZE[0] // 4),
                    Image.NEAREST
                )
                lane = torch.from_numpy(np.array(lane)).long()
            else:
                lane = torch.zeros(
                    (INPUT_SIZE[0] // 4, INPUT_SIZE[1] // 4),
                    dtype=torch.long
                )
            sample['lanes'] = lane

        return sample


def get_dataloaders(root_dir, tasks=None, batch_size=8, num_workers=2,
                    seg_root=None, depth_root=None):
    """Create train and val dataloaders for BDD100K."""
    train_dataset = BDD100KDataset(
        root_dir, split='train', tasks=tasks,
        seg_root=seg_root, depth_root=depth_root,
    )
    val_dataset = BDD100KDataset(
        root_dir, split='val', tasks=tasks,
        seg_root=seg_root, depth_root=depth_root,
    )

    train_loader = DataLoader(
        train_dataset,
        batch_size=batch_size,
        shuffle=True,
        num_workers=num_workers,
        pin_memory=True,
        drop_last=True,
    )

    val_loader = DataLoader(
        val_dataset,
        batch_size=batch_size,
        shuffle=False,
        num_workers=num_workers,
        pin_memory=True,
    )

    return train_loader, val_loader
